cart/urls.py
from django.conf.urls import url
from .views import add_to_cart, view_cart, remove_from_cart,remove_all_from_cart
urlpatterns = [
    url(r'^add_to_cart/(?P<id>\d+)$', add_to_cart, name='add_to_cart_link'),
    url(r'^remove_from_cart/(?P<id>\d+)$', remove_from_cart, name='remove_from_cart_link'),
    url(r'^view_cart/$', view_cart),
    url(r'^clear_cart/$', remove_all_from_cart, name='remove_all_from_cart_link')
]

checkout/urls.py
from django.conf.urls import url, include
from .views import checkout

urlpatterns = [
    url(r'^$', checkout, name='checkout_link')
]

tracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from tracker_app import urls as trackerapp_url
from cart import urls as cart_urls
from tracker_app.views import home, add_bug, edit_bug,delete_bug, feature, add_feature, edit_feature
from django.conf import settings
from django.conf.urls.static import static 
from django.shortcuts import HttpResponse
from checkout import urls as checkout_url
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include(trackerapp_url.urlpatterns)),
    url(r'^$', home, name="home"),
    url(r'add/$', add_bug,name="add_bug"),
    url(r'edit/(?P<id>\d+)$', edit_bug),
    url(r'delete/(?P<id>\d+)$', delete_bug,name="delete_bug"),
    url(r'add_feature/$', add_feature,name="add_feature"),
    url(r'edit_feature/(?P<id>\d+)$', edit_feature, name="edit_feature"),
    url(r'^feature/', feature, name="feature"),
    url(r'^cart/', include(cart_urls.urlpatterns)),
    url(r'^checkout/', include(checkout_url.urlpatterns))
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
from django.contrib.auth.models import User
from tracker_app.models import Feature
# # Create your models here.

# Create your models here.
class Order(models.Model):
    
    ordered_by = models.ForeignKey(User, on_delete = models.CASCADE, related_name='orders')
    stripe_token = models.CharField(max_length=1000, blank=False)
    purchased_at = models.DateTimeField(blank=False)
    name = models.CharField(max_length=255, blank=False)
    address =models.CharField(max_length=255, blank=False)
    
    def __str__(self):
        return "Order - " + str(self.id)
    
class OrderLineItem(models.Model):
    
    post = models.ForeignKey(Feature, on_delete=models.CASCADE, related_name = 'orders')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name = 'order_line_items')
    quantity = models.IntegerField()
    def __str__(self):
        return "Order {} - Product {}".format(self.order_id, self.post_id)

checkout/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('name', 'address')
        
    

class PaymentForm(forms.Form):
    # cc, cvc, expiry date
    MONTH_CHOICES = [(i, i) for i in range(1, 12)]
    YEAR_CHOICES = [(i, i) for i in range(2019, 2036)]

    credit_card_number = forms.CharField(label='Credit card number', required=False)
    cvv = forms.CharField(label='Security code (CVV)', required=False)
    expiry_month = forms.ChoiceField(label='Month', choices=MONTH_CHOICES, required=False)
    expiry_year = forms.ChoiceField(label='Year', choices=YEAR_CHOICES, required=False)
    stripe_id = forms.CharField(widget=forms.HiddenInput)

checkout/views.py
from django.shortcuts import render, HttpResponse
from django.conf import settings
from .forms import OrderForm, PaymentForm
from django.utils import timezone
from tracker_app.models import Feature
from .models import Order, OrderLineItem
from django.core.mail import send_mail

import stripe

# Create your views here.
def checkout(request):
    # this is to show the form
    if request.method == 'GET':
        cart = request.session.get('cart', {})
        order_form = OrderForm()
        payment_form = PaymentForm()
        return render(request, 'checkout.html', {
            'cart': cart, 
            'order_form':order_form,
            'payment_form':payment_form,
            'stripe_publishable_key':settings.STRIPE_PUBLISHABLE_KEY
        })
    else:
        # set the secret key for Stripe
        stripe.api_key = settings.STRIPE_SECRET_KEY
        
        # to process the post via POST
        cart = request.session.get('cart', {})
        total_cost = 0
        for cart_item in cart.values():
            total_cost = cart_item['qty'] * cart_item['product']['price']
           
        order_form = OrderForm(request.POST)
        payment_form = PaymentForm(request.POST) 
        
        if order_form.is_valid() and payment_form.is_valid():
            order = order_form.save(commit=False)
            order.stripe_token = request.POST.get('stripe_id')
            order.purchased_at = timezone.now()
            order.ordered_by = request.user
            order.save()
            
            for cart_item in cart.values():
                post_id = cart_item['product']['id']
                post = Feature.objects.get(pk=post_id)
                order_line_item = OrderLineItem(
                    post = post,
                    order = order,
                    quantity = cart_item['qty']
                )
                order_line_item.save()
                
            try:
                customer = stripe.Charge.create(
                    amount = int(total_cost * 100),
                    currency = "sgd",
                    description = "Order ID #" + str(order.id),
                    source= order.stripe_token
                    )
            except stripe.error.CardError as e: 
                print (e)
                return HttpResponse("Card problem")
                
            if customer.paid:
                # request.session['cart'] = {}
                subject = "Your invoice for your order " + str(order.id)
                message = "Your order has been processed and will be shipped to you shortly"
                email_from = settings.EMAIL_HOST_USER
             
                send_to = ['chorkunxin@gmail.com']
                send_mail(subject, message, email_from, send_to)
                return  HttpResponse("Payment successful")
                
            else:
                return HttpResponse("Payment failed")
            
        else:
            print(order_form.is_valid())
            print(payment_form.is_valid())
            print(payment_form.errors)
        
            
        

checkout/templates/checkout.html
{% extends 'layout.html' %}

{% block js_includes %}
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script>
/* global $ */
$(function(){

    $('#payment-form').submit(function(event){
        // Prevent the default of behaviour of clicking on the form's submit button
        // In general, preventDefault() can be used to override the browser's defualt behaviour
        event.preventDefault();
        
        let stripe_publishable_key = '{{stripe_publishable_key }}';
       
        /* global Stripe */
        Stripe.publishableKey = stripe_publishable_key;
        // This is to create a card object according to the Stripe's specification
        var card = {
            number: $("#id_credit_card_number").val(),
            expMonth: $("#id_expiry_month").val(),
            expYear: $("#id_expiry_year").val(),
            cvc: $("#id_cvv").val()
        };
        let form = this;
        
        Stripe.createToken(card, function(status, response){
            if (status == 200) {
                $('#id_credit_card_number').removeAttr('name');
                $('#id_cvv').removeAttr('name');
                $("#id_expiry_month").removeAttr('name');
                $("#id_expiry_year").removeAttr('name');
                $("#id_stripe_id").val(response.id);
                form.submit();
            }  else {
                alert("Credit card problem");
            }
        })
        
      
    })
});
</script>
{% endblock %}

{%block content %}
<h1>Checkout</h1>
<p>
    Please double check that you really want buy those things because there will be no refund
</p>
<ul>
    {% for key,value in cart.items %}
    <li>{{value.product.title}}
    <br>Quantity:{{value.qty}}
    {% endfor %}
</ul>

    <form method="POST" id='payment-form'>
    {% csrf_token %}
    {{ order_form.as_p }}
    
    {{ payment_form.as_p }}
    
    <input type='submit'>
</form>

{%endblock%}